# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Configuration for a static website. Requests for the site root are
# redirected to /intl/[LANG]/ depending on the browser.
#
# https://cloud.google.com/appengine/docs/standard/python3/config/appref

runtime: python37

handlers:

  # The website root page is handled by a small Python application.
  - url: /$
    script: auto
    secure: always

  - url: /(.*/)?$
    static_files: dist/\1index.html
    upload: dist/.*index.html
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"

  - url: /.*
    static_dir: dist
    secure: always
    http_headers:
      Strict-Transport-Security: "max-age=2592000; includeSubdomains"
      X-Content-Type-Options: "nosniff"
      X-Frame-Options: "DENY"
      X-XSS-Protection: "1; mode=block"
